EcouzTourism/Controllers/VillaNumberController.cs
using EcouzTourism.Application.Common.Interfaces;
using EcouzTourism.Domain.Entities;
using EcouzTourism.Infrastructure.Data;
using EcouzTourism.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EcouzTourism.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VillaNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = _unitOfWork.VillaNumber.GetAll(includeProperties: "Villa");
            return View(villaNumbers);
        }
        public IActionResult Create()
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(villaNumberVM);
        }
       

        [HttpPost]
        public IActionResult Create(VillaNumberVM obj)
        {
            bool roomNumberExists = _unitOfWork.VillaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

            
            if (ModelState.IsValid &&!roomNumberExists)
            {

                _unitOfWork.VillaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = $"Villa number Has been created successfully";
                return RedirectToAction(nameof(Index));
            }
            if (roomNumberExists)
            {
                TempData["error"] = "The Villa number Already Exists . ";
            }
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj); 
        }
        public IActionResult Update(int VillaNumberId)
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == VillaNumberId)
            };
            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
        }


        [HttpPost]
        public IActionResult Update(VillaNumberVM villaNumberVM)
        {

            if (ModelState.IsValid)
            {

                _unitOfWork.VillaNumber.Update(villaNumberVM.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = $"Villa number Has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            
            villaNumberVM.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            
            return View(villaNumberVM);
        }
        public IActionResult Delete(int VillaNumberId)
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == VillaNumberId)
            };
            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
        }

        [HttpPost]
        public IActionResult Delete(VillaNumberVM villaNumberVM)
        {
            VillaNumber? objFromDb = _unitOfWork.VillaNumber.Get
                (u => u.Villa_Number == villaNumberVM.VillaNumber.Villa_Number);

            if(objFromDb is not null)
            {
                _unitOfWork.VillaNumber.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "the villa number has been deleted successfully";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "The villa number could not be deleted";
            return View();
            
        }
    }
}

EcouzTourism/Views/VillaNumber/Create.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-2 neon-text">
    <h1>
        Create Villa Number
    </h1>
    <div class="card-body  p-2">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <select asp-for = "@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                        class="form-select border shadow"    
                    >
                        <option disabled selected> Select Villa </option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger neon-text-danger"></span>
                </div>
               
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-outline-success w-100 neon-button-success">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-outline-secondary w-100  neon-button">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

EcouzTourism/Views/VillaNumber/Delete.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-2 ">
    <h4 class="neon-text-danger">
        Are you Sure to Delete This  Villa Number ? 
    </h4>
    <div class="card-body  p-2">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="VillaNumber.Villa_Number" hidden />
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <select disabled asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected> Select Villa </option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger neon-text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-outline-danger w-100 neon-button-danger">
                            <i class="bi bi-check-circle"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-outline-secondary w-100  neon-button">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

EcouzTourism/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>



<div class="w-100 card border-0 p-4">
    @* <div class="card-header  ml-0 py-3 neon-card ">
    <div class="row ">
    <div class="col-12 text-center  ">
    <h2 class="text-white py-2">Villa List</h2>
    </div>
    </div>
    </div> *@
    <div class="card-body  p-4 ">
        <h1 class="neon-text">
            Villa Number List
        </h1>
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn text-white neon-button-success">
                    <i class="bi bi-plus-circle"></i> Create Villa Number
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped neon-card">
            <thead class="neon-text">
                <tr>
                    <th>Villa Name</th>
                    <th>Villa Number</th>
                    <th>Special Details</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Villa.Name</td>
                        <td>@obj.Villa_Number</td>
                        <td>@obj.SpecialDetails</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-VillaNumberId="@obj.Villa_Number"
                                   class="btn btn-outline-info mx-2 neon-button-info">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-VillaNumberId="@obj.Villa_Number"
                                   class="btn btn-outline-danger mx-2 neon-button-danger">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EcouzTourism/Views/VillaNumber/Update.cshtml
@model VillaNumberVM

<div class="w-100 card border-0 p-2 ">
    <h1 class="neon-text">
        Update Villa Number
    </h1>
    <div class="card-body  p-2">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="VillaNumber.Villa_Number"  hidden/>
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected> Select Villa </option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger neon-text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2 neon-text"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger neon-text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-outline-info w-100 neon-button-info">
                            <i class="bi bi-check-circle"></i> Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-outline-secondary w-100  neon-button">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}